### model
model_name_or_path: /data/wangzhuoshang/project/mgtd-sys/detector/ckpt/glm-4-9b-chat
trust_remote_code: true

### method
stage: sft
do_train: true
do_eval: true
eval_strategy: steps
eval_steps: 500
finetuning_type: lora
lora_rank: 8
lora_target: query_key_value

### dataset
dataset: nlpcc25_task1_train_10000  # 用于训练的数据集名称。使用逗号分隔多个数据集。
template: glm4  # 训练和推理时构造 prompt 的模板
eval_dataset: nlpcc25_task1_dev  # 用于评估的数据集名称。使用逗号分隔多个数据集。
compute_accuracy: true  # 在评估时计算token级别的准确率
cutoff_len: 1024  # 截断长度
# max_samples: 1000  # 训练集样本截断数量
overwrite_cache: true  # 是否覆盖缓存的训练和评估数据集
preprocessing_num_workers: 16
dataloader_num_workers: 4

### output
output_dir: /data/wangzhuoshang/project/mgtd-sys/detector/ckpt/glm-4-9b-chat-lora-10000/
logging_steps: 10
save_steps: 500
plot_loss: true  # 画损失图像
overwrite_output_dir: true
save_only_model: false

### train
per_device_train_batch_size: 4  # 训练集批次大小，根据gpu使用情况调整
per_device_eval_batch_size: 4  # 验证集批次大小，根据gpu使用情况调整
gradient_accumulation_steps: 8
learning_rate: 5.0e-5
num_train_epochs: 3.0
lr_scheduler_type: cosine
warmup_ratio: 0.1
bf16: true
ddp_timeout: 180000000
resume_from_checkpoint: null

### eval
# eval_dataset: alpaca_en_demo
# val_size: 0.1
# per_device_eval_batch_size: 1
# eval_strategy: steps
# eval_steps: 500

### generation
do_sample: false  # 确定性任务不采样
